name: Deploy Application

on:
  push:
    branches: [ production ]

jobs:
  deploy_app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Copy files to SSH server
      uses: nogsantos/scp-deploy@master
      with:
        src: './assets ./components ./vendor ./views index.php routes.php'
        remote: ${{ secrets.SSH_PATH }}
        host: ${{ secrets.SSH_HOSTNAME }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}